---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart trilium next server
  ansible.builtin.systemd:
    name: "{{ trilium_next_server_service_name }}"
    state: restarted