packer {
  required_plugins {
    ansible = {
      source  = "github.com/hashicorp/ansible"
      version = "~> 1"
    }
    qemu = {
      source  = "github.com/hashicorp/qemu"
      version = "~> 1"
    }
  }
}

variable "password" {
  type = string
  default = ""
  sensitive = true
}

variable "luks_passphrase" {
  type = string
  default = ""
  sensitive = true
}

variable "random_seed_for_oath" {
  type = string
  default = ""
  sensitive = true
}

variable "resource_group_for_image" {
  type = string
  default = ""
}

variable "ssh_authorized_keys_base64" {
  type = string
  default = ""
  sensitive = true
}

variable "storage_account_name" {
  type = string
  default = ""
}

variable "username" {
  type = string
  default = ""
}

source "qemu" "autogenerated_1" {
  accelerator      = "kvm"
  boot_command     = ["<enter><wait60><enter>", "curl -sfSLO http://{{ .HTTPIP }}:{{ .HTTPPort }}/packer.sh<enter><wait>", "chmod +x *.sh<enter>", "./packer.sh<enter>"]
  boot_wait        = "20s"
  cpus             = 2
  disk_cache       = "unsafe"
  disk_compression = true
  disk_discard     = "unmap"
  disk_size        = "4000M"
  firmware         = "/usr/share/OVMF/x64/OVMF_CODE.fd"
  format           = "raw"
  headless         = true
  http_directory   = "http"
  iso_checksum     = "none"
  iso_url          = "https://mirror.puzzle.ch/archlinux/iso/latest/archlinux-x86_64.iso"
  output_directory = "./packer_output/qemu"
  qemuargs         = [["-m", "2048M"], ["-boot", "menu=on,splash-time=10000"]]
  shutdown_command = "sudo systemctl poweroff"
  ssh_password     = "root"
  ssh_timeout      = "20m"
  ssh_username     = "root"
}

build {
  sources = ["source.qemu.autogenerated_1"]

  provisioner "ansible" {
    extra_arguments = ["--extra-vars", "username=${var.username} create_minimal_image=true luks_passphrase=${var.luks_passphrase} password=${var.password} ssh_authorized_keys_base64=${var.ssh_authorized_keys_base64} random_seed=${var.random_seed_for_oath}", "-v"]
    playbook_file   = "playbooks/1_archlinux-server-install-playbook.yml"
  }
}