name: packer
on:
  push:
env:
  PRODUCT_VERSION: "1.8.6" # or: "latest"
jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          github-server-url: 'https://manolito.wanip.ch/git/'

      - name: Clone external repository with subpath
        run: |
          # Replace "EXTERNAL_REPO_URL" with the URL of the external repository and "SUBPATH" with the desired subpath
          git clone --branch master https://manolito.wanip.ch/git/manuel/azure-archlinux-image.git
      
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ./server-azure-ubuntu-packer.json"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./server-azure-ubuntu-packer.json"