name: packer
on:
  push:
jobs:
  packer:
    runs-on: self-hosted
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run `packer validate`
        id: validate
        run: |
          packer plugins install github.com/hashicorp/qemu
          packer plugins install github.com/hashicorp/ansible
          packer validate \
          -var "username=manuel" \
          -var "smtp_server_incl_port=smtp.gmail.com:587" \
          -var "smtp_user=\"${{ secrets.SMTP_USER }}\"" \
          -var "smtp_pass=\"${{ secrets.SMTP_PASS }}\"" \
          -var "smtp_sender=\"${{ secrets.SMTP_SENDER }}\"" \
          -var "notification_email=\"${{ secrets.NOTIFICATION_EMAIL }}\"" \
          -var "ssh_authorized_keys_base64=\"${{ secrets.SSH_AUTHORIZED_KEYS_BASE64 }}\"" \
          -var "storage_account_name=${{ vars.IMAGE_STORAGE_ACCOUNT }}" \
          -var "password=${{ secrets.PASSWORD }}" \
          -var "random_seed_for_oath=${{ secrets.OATH_SEED }}" \
          -var "resource_group_for_image=${{ vars.IMAGE_RESOURCE_GROUP }}" \
          -var "luks_passphrase=${{ secrets.LUKS_PASSPHRASE }}" \
          ./server-archlinux-packer.pkr.hcl

      - name: Run `packer build`
        id: build
        run: | 
          PACKER_LOG=1 packer build \
          -var "username=manuel" \
          -var "smtp_server_incl_port=smtp.gmail.com:587" \
          -var "smtp_user=\"${{ secrets.SMTP_USER }}\"" \
          -var "smtp_pass=\"${{ secrets.SMTP_PASS }}\"" \
          -var "smtp_sender=\"${{ secrets.SMTP_SENDER }}\"" \
          -var "notification_email=\"${{ secrets.NOTIFICATION_EMAIL }}\"" \
          -var "ssh_authorized_keys_base64=\"${{ secrets.SSH_AUTHORIZED_KEYS_BASE64 }}\"" \
          -var "storage_account_name=${{ vars.IMAGE_STORAGE_ACCOUNT }}" \
          -var "password=${{ secrets.PASSWORD }}" \
          -var "random_seed_for_oath=${{ secrets.OATH_SEED }}" \
          -var "resource_group_for_image=${{ vars.IMAGE_RESOURCE_GROUP }}" \
          -var "luks_passphrase=${{ secrets.LUKS_PASSPHRASE }}" \
          ./server-archlinux-packer.pkr.hcl