name: packer
on:
  push:
env:
  PRODUCT_VERSION: "1.8.6" # or: "latest"
jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ./server-azure-ubuntu-packer.json"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./server-azure-ubuntu-packer.json"