name: packer
on:
  push:
env:
  PRODUCT_VERSION: "1.8.6" # or: "latest"
jobs:
  packer:
    runs-on: self-hosted
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run `packer validate`
        id: validate
        run: | 
          packer validate \
          -var "username=manuel" \
          -var "publickey=\"${{ secrets.PUBLIC_KEY }}\"" \
          -var "storage_account_name=TODO" \
          -var "password=${{ secrets.PASSWORD }}" \
          -var "random_seed_for_oath=${{ secrets.OATH_SEED }}" \
          ./server-azure-ubuntu-packer.json