name: packer
on:
  push:
env:
  IMAGE_STORAGE_ACCOUNT: "mdgcorpstorage"
  IMAGE_RESOURCE_GROUP: "mdgcorp-storage"
jobs:
  packer:
    runs-on: self-hosted
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run `packer validate`
        id: validate
        run: | 
          packer validate \
          -var "username=manuel" \
          -var "ssh_authorized_keys_bas64=\"${{ secrets.SSH_AUTHORIZED_KEYS_BASE64 }}\"" \
          -var "storage_account_name=$IMAGE_STORAGE_ACCOUNT" \
          -var "password=${{ secrets.PASSWORD }}" \
          -var "random_seed_for_oath=${{ secrets.OATH_SEED }}" \
          -var "resource_group_for_image=$IMAGE_RESOURCE_GROUP" \
          ./server-archlinux-packer.json

      - name: Run `packer build`
        id: build
        run: | 
          PACKER_LOG=1 packer build \
          -var "username=manuel" \
          -var "ssh_authorized_keys_bas64=\"${{ secrets.SSH_AUTHORIZED_KEYS_BASE64 }}\"" \
          -var "storage_account_name=$IMAGE_STORAGE_ACCOUNT" \
          -var "password=${{ secrets.PASSWORD }}" \
          -var "random_seed_for_oath=${{ secrets.OATH_SEED }}" \
          -var "resource_group_for_image=$IMAGE_RESOURCE_GROUP" \
          ./server-archlinux-packer.json