name: packer
on:
  push:
jobs:
  packer:
    runs-on: self-hosted
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Run `packer init`
        id: init
        run: |
          packer init ./server-archlinux-packer.pkr.hcl

      - name: Run `packer validate`
        id: validate
        run: |
          packer validate \
          -var "username=\"${{ vars.USERNAME }}\"" \
          -var "ssh_authorized_keys_base64=\"${{ secrets.SSH_AUTHORIZED_KEYS_BASE64 }}\"" \
          -var "storage_account_name=\"${{ vars.IMAGE_STORAGE_ACCOUNT }}\"" \
          -var "password=\"${{ secrets.PASSWORD }}\"" \
          -var "random_seed_for_oath=\"${{ secrets.OATH_SEED }}\"" \
          -var "resource_group_for_image=\"${{ vars.IMAGE_RESOURCE_GROUP }}\"" \
          -var "luks_passphrase=\"${{ secrets.LUKS_PASSPHRASE }}\"" \
          ./server-archlinux-packer.pkr.hcl

      - name: Run `packer build`
        id: build
        run: | 
          packer build \
          -var "username=\"${{ vars.USERNAME }}\"" \
          -var "ssh_authorized_keys_base64=\"${{ secrets.SSH_AUTHORIZED_KEYS_BASE64 }}\"" \
          -var "storage_account_name=\"${{ vars.IMAGE_STORAGE_ACCOUNT }}\"" \
          -var "password=\"${{ secrets.PASSWORD }}\"" \
          -var "random_seed_for_oath=\"${{ secrets.OATH_SEED }}\"" \
          -var "resource_group_for_image=\"${{ vars.IMAGE_RESOURCE_GROUP }}\"" \
          -var "luks_passphrase=\"${{ secrets.LUKS_PASSPHRASE }}\"" \
          ./server-archlinux-packer.pkr.hcl
