---
- name: Add user
  command:
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        useradd -m {{ username }} -G wheel -s /bin/bash
        echo -e "{{ password }}\n{{ password }}" | passwd {{ username }}
        mkdir /home/{{ username }}/.ssh
        echo "{{ ssh_authorized_keys_bas64 | b64decode }}" >> /home/{{ username }}/.ssh/authorized_keys
        # look root
        passwd -l root
       
- name: allow admin user passwordless sudo
  ansible.builtin.lineinfile:
    path: /mnt/etc/sudoers
    regexp: '^{{ username }} ALL=(ALL:ALL) NOPASSWD:ALL'
    line: "{{ username }} ALL=(ALL:ALL) NOPASSWD:ALL"

- name: Install oath-toolkit
  command:
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        pacman -Sy --noconfirm oath-toolkit

- name: allow sshd ChallengeResponseAuthentication 
  ansible.builtin.lineinfile:
    path: /mnt/etc/ssh/sshd_config
    regexp: ^\#*ChallengeResponseAuthentication(.*)$
    line: ChallengeResponseAuthentication yes

- name: allow sshd UsePAM 
  ansible.builtin.lineinfile:
    path: /mnt/etc/ssh/sshd_config
    regexp: ^\#*UsePAM(.*)$
    line: UsePAM yes

- name: disable Passwordauthentication 
  ansible.builtin.lineinfile:
    path: /mnt/etc/ssh/sshd_config
    regexp: ^\#*PasswordAuthentication(.*)$
    line: PasswordAuthentication no

- name: set oath config
  copy:
    owner: root
    group: root
    mode: '0600'
    force: yes
    dest: /mnt/etc/users.oath
    content: |
      # Option User Prefix Seed
      HOTP/T30/6 {{ username }} - {{ random_seed }}

- name: set pam to use oath
  lineinfile:
    path: /mnt/etc/pam.d/sshd
    insertbefore: BOF
    line: auth	  sufficient pam_oath.so usersfile=/etc/users.oath window=30 digits=6