---
- name: Add user
  when: username is defined
  command:
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        useradd -m {{ username }}
        {% if ansible_ssh_pass is defined %}
        echo -e "{{ ansible_ssh_pass }}\n{{ ansible_ssh_pass }}" | passwd {{ username }}
        {% endif %}
        gpasswd -a {{ username }} wheel
        gpasswd -a {{ username }} uucp
        mkdir /home/{{ username }}/.ssh
        echo "{{ user_ssh_public_key | default("") }}" >> /home/{{ username }}/.ssh/authorized_keys
       
- name: allow admin user passwordless sudo
  when: username is defined
  ansible.builtin.lineinfile:
    path: /mnt/etc/sudoers
    regexp: '^{{ username }} ALL=(ALL:ALL) NOPASSWD:ALL'
    line: "{{ username }} ALL=(ALL:ALL) NOPASSWD:ALL"