---
- name: Format root partition with btrfs
  when: not root_mounted
  filesystem: 
    dev: "{{ install_device_name }}{{ root_partition_number }}"
    fstype: btrfs
    force: yes

- name: Mount Root partition
  when: not root_mounted
  mount:
    path: "/mnt"
    src: "{{ install_device_name }}{{ root_partition_number }}"
    state: mounted
    fstype: btrfs
    opts: compress=zstd:{{ zstd_compression }},noatime,discard=async,autodefrag

- name: create btrfs subvolumes
  shell: | 
    btrfs filesystem label /mnt/ {{ root_filesystem_label }}
    btrfs su cr /mnt/@
    btrfs su cr /mnt/@home
    btrfs su cr /mnt/@root
    btrfs su cr /mnt/@srv
    btrfs su cr /mnt/@log
    btrfs su cr /mnt/@cache
    btrfs su cr /mnt/@vartmp
    btrfs su set-default /mnt/@
    umount /mnt

- name: Mount subvol @ as root partition
  mount:
    path: "/mnt"
    src: "{{ install_device_name }}{{ root_partition_number }}"
    state: mounted
    fstype: btrfs
    opts: defaults,compress=zstd:{{ zstd_compression }},noatime,discard=async,autodefrag,subvol=@

- name: create folders for btrfs subvolumes
  command: mkdir -p /mnt/{{ item }}
  loop:
    - home
    - root
    - srv
    - var/log
    - var/cache/
    - var/tmp

- name: Mount home subvol partition
  mount:
    path: "/mnt/home"
    src: "{{ install_device_name }}{{ root_partition_number }}"
    state: mounted
    fstype: btrfs
    opts: defaults,nosuid,nodev,compress=zstd:{{ zstd_compression }},noatime,discard=async,autodefrag,subvol=@home

- name: Mount root subvol partition
  mount:
    path: "/mnt/root"
    src: "{{ install_device_name }}{{ root_partition_number }}"
    state: mounted
    fstype: btrfs
    opts: defaults,compress=zstd:{{ zstd_compression }},noatime,discard=async,autodefrag,subvol=@root

- name: Mount srv subvol partition
  mount:
    path: "/mnt/srv"
    src: "{{ install_device_name }}{{ root_partition_number }}"
    state: mounted
    fstype: btrfs
    opts: defaults,compress=zstd:{{ zstd_compression }},noatime,discard=async,autodefrag,subvol=@srv

- name: Mount /var/log subvol partition
  mount:
    path: "/mnt/var/log"
    src: "{{ install_device_name }}{{ root_partition_number }}"
    state: mounted
    fstype: btrfs
    opts: defaults,nosuid,noexec,nodev,compress=zstd:{{ zstd_compression }},noatime,discard=async,autodefrag,subvol=@log

- name: Mount /var/cache subvol partition
  mount:
    path: "/mnt/var/cache"
    src: "{{ install_device_name }}{{ root_partition_number }}"
    state: mounted
    fstype: btrfs
    opts: defaults,compress=zstd:{{ zstd_compression }},noatime,discard=async,autodefrag,subvol=@cache

- name: Mount /var/tmp subvol partition
  mount:
    path: "/mnt/var/tmp"
    src: "{{ install_device_name }}{{ root_partition_number }}"
    state: mounted
    fstype: btrfs
    opts: defaults,compress=zstd:{{ zstd_compression }},noatime,nodev,nosuid,noexec,discard=async,autodefrag,subvol=@vartmp

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /mnt/boot
    state: directory

- name: Mount boot partition
  mount:
    path: "/mnt/boot"
    src: "{{ install_device_name }}1"
    state: mounted
    fstype: vfat
