---
- name: Format root partition with btrfs
  when: not root_mounted
  filesystem: 
    dev: "{{ install_device_name }}{{ root_partition_number }}"
    fstype: btrfs
    force: yes

- name: Mount Root partition
  when: not root_mounted
  mount:
    path: "/mnt"
    src: "{{ install_device_name }}{{ root_partition_number }}"
    state: mounted
    fstype: btrfs
    opts: compress=zstd:3,noatime,discard

- name: Create a directory if it does not exist
  when: bootloader != "bios"
  ansible.builtin.file:
    path: /mnt/efi
    state: directory

- name: Mount boot partition
  when: not boot_mounted and bootloader != "bios"
  mount:
    path: "/mnt/efi"
    src: "{{ install_device_name }}1"
    state: mounted
    fstype: vfat