---
- name: Format root partition with btrfs
  when: not root_mounted
  filesystem: 
    dev: "{{ install_device_name }}{{ root_partition_number }}"
    fstype: btrfs
    force: yes

- name: Mount Root partition
  when: not root_mounted
  mount:
    path: "/mnt"
    src: "{{ install_device_name }}{{ root_partition_number }}"
    state: mounted
    fstype: btrfs
    opts: compress-force=zstd,noatime,discard=async,autodefrag

- name: Create /var directory
  ansible.builtin.file:
    path: /mnt/var
    state: directory

- name: Create /var/cache directory
  ansible.builtin.file:
    path: /mnt/var/cache
    state: directory

- name: Create /var/cache/pacman directory
  ansible.builtin.file:
    path: /mnt/var/cache/pacman
    state: directory

- name: create btrfs subvolumes
  command:
    argv:
      - btrfs subvol create /mnt/var/cache/pacman/pkg
      - btrfs subvol create /mnt/var/log
      - btrfs subvol create /mnt/var/abs
      - btrfs subvol create /mnt/var/tmp
      - btrfs subvol create /mnt/srv

- name: Create a directory if it does not exist
  when: bootloader != "bios"
  ansible.builtin.file:
    path: /mnt/efi
    state: directory

- name: Mount boot partition
  when: not boot_mounted and bootloader != "bios"
  mount:
    path: "/mnt/efi"
    src: "{{ install_device_name }}1"
    state: mounted
    fstype: vfat