---
- name: Install caddy
  command:
    argv:
      pacman -Sy --noconfirm caddy
      firewall-offline-cmd --zone=public --add-port=80/tcp
      firewall-offline-cmd --zone=public --add-port=443/tcp

- name: set caddyfile
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/etc/caddy/Caddyfile
    content: |
      # Replace domain with the fqdn during cloud-init
      <domain> {
        reverse_proxy /admin/* localhost:9090 {
          transport http {
              tls_insecure_skip_verify
          }
        }
      }