---
- name: Install fluent-bit
  command: 
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        sudo -u {{ username }} yay -Sy --noconfirm --aur fluent-bit

- name: Create /usr/lib/systemd/system/fluent-bit.service.d directory
  ansible.builtin.file:
    path: /usr/lib/systemd/system/fluent-bit.service.d
    state: directory

- name: set fluent-bit systemd proxy settings
  copy:
    owner: root
    group: root
    force: yes
    dest: /usr/lib/systemd/system/fluent-bit.service.d/http_proxy.conf
    content: |
      [Service]
      Environment="http_proxy=http://127.0.0.1:8888"
      Environment="https_proxy=http://127.0.0.1:8888"
      Environment="HTTP_PROXY=http://127.0.0.1:8888"
      Environment="HTTPS_PROXY=http://127.0.0.1:8888"

- name: set fluent-bit.conf
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/etc/fluent-bit/fluent-bit.conf
    content: |
      [SERVICE]
        flush        1
        daemon       Off
        log_level    info
        parsers_file parsers.conf
        plugins_file plugins.conf
        http_server  Off
        http_listen  0.0.0.0
        http_port    2020
        storage.metrics on
        # storage.path /tmp/storage
        # storage.sync normal
        # storage.checksum off
        # storage.backlog.mem_limit 5M

    [INPUT]
        name systemd
        tag  *

    [FILTER]
        Name     grep
        Match    *
        Exclude  _SYSTEMD_UNIT fluent-bit\.service|waagent\.service|init\.scope|pmlogger_farm_check\.service
    
    [FILTER]
        Name record_modifier
        Match *
        Remove_Key _COMM
        Remove_Key _EXE
        Remove_Key _SYSTEMD_CGROUP
        Remove_Key _SYSTEMD_INVOCATION_ID
        Remove_Key _CMDLINE
        Remove_Key _PID
        Remove_Key _MACHINE_ID
        Remove_Key _SYSTEMD_SLIDE
        Remove_Key _BOOT_ID
        Remove_Key _AUDIT_FIELD_EXE
        Remove_Key _AUDIT_FIELD_TERMINAL
        Remove_Key JOB_TYPE
        Remove_Key CODE_FUNC
        Remove_Key _CAP_EFFECTIVE
        Remove_Key _SELINUX_CONTEXT
        Remove_Key TID
        Remove_Key _AUDIT_LOGINUID
        Remove_Key sequence_d

    [OUTPUT]
        Name        azure
        Match       *
        Customer_ID <customerid>
        Shared_Key  <sharedkey>