---
- name: Install cockpit and open firewalld port
  ignore_errors: true
  command:
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        pacman -Sy --noconfirm cockpit cockpit-machines cockpit-podman cockpit-packagekit cockpit-storaged udisks2
        firewall-offline-cmd --add-rich-rule='rule port port=9090 protocol=tcp accept limit value="20/m"'
        systemctl enable cockpit.socket

- name: set cockpit pam to use oath
  when: cloud_init
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/etc/pam.d/cockpit
    content: |
      auth      auth	  required pam_oath.so usersfile=/etc/users.oath window=30 digits=6
      auth      include   system-remote-login
      account   include   system-remote-login
      password  include   system-remote-login
      session   include   system-remote-login