---
- name: Install fluent-bit
  command: 
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        sudo -u {{ username }} yay -Sy --noconfirm --aur fluent-bit

- name: set fluent-bit http proxy var in systemd service
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/fluent-bit.service
    line: Environment="HTTP_PROXY=http://127.0.0.1:8888"
    insertafter: ^[Service]$
    create: yes

- name: set fluent-bit.conf
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/etc/fluent-bit/fluent-bit.conf
    content: |
      [SERVICE]
        flush        1
        daemon       Off
        log_level    info
        parsers_file parsers.conf
        plugins_file plugins.conf
        http_server  Off
        http_listen  0.0.0.0
        http_port    2020
        storage.metrics on
        # storage.path /tmp/storage
        # storage.sync normal
        # storage.checksum off
        # storage.backlog.mem_limit 5M

    [INPUT]
        name systemd
        tag  *

    [OUTPUT]
        Name        azure
        Match       *
        Customer_ID <customerid>
        Shared_Key  <sharedkey>