---
- name: Install cloud-init
  ignore_errors: true
  when: cloud_init
  command:
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        pacman -Sy --noconfirm cloud-init cloud-guest-utils gptfdisk
        systemctl enable cloud-init.service
        systemctl enable cloud-final.service

- name: set cloud-init cloud.cfg
  when: cloud_init
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/etc/cloud/cloud.cfg
    content: |
      users:
        - name: {{ username }}
          sudo: ["ALL=(ALL) NOPASSWD:ALL"]
          shell: /bin/bash
          groups: users, wheel
          lock_passwd: true
          ssh_authorized_keys:
            - {{ user_ssh_public_key }}
      disable_root: true
      preserve_hostname: false
      datasource_list: [ Azure ]

      # The modules that run in the 'init' stage
      cloud_init_modules:
      - migrator
      - seed_random
      - bootcmd
      - write-files
      - growpart
      - resizefs
      - disk_setup
      - mounts
      - set_hostname
      - update_hostname
      - update_etc_hosts
      - ca-certs
      - rsyslog
      - users-groups
      - ssh

      # The modules that run in the 'config' stage
      cloud_config_modules:
      - ssh-import-id
      - locale
      - set-passwords
      - ntp
      - timezone
      - runcmd

      # The modules that run in the 'final' stage
      cloud_final_modules:
      - package-update-upgrade-install
      - write-files-deferred
      - mcollective
      - reset_rmc
      - refresh_rmc_and_interface
      - rightscale_userdata
      - scripts-vendor
      - scripts-per-once
      - scripts-per-boot
      - scripts-per-instance
      - scripts-user
      - ssh-authkey-fingerprints
      - keys-to-console
      - install-hotplug
      - phone-home
      - final-message
      - power-state-change

      system_info:
        distro: arch
        paths:
            cloud_dir: /var/lib/cloud/
            templates_dir: /etc/cloud/templates/
        ssh_svcname: sshd   

      #cloud-config
      device_aliases: {'ephemeral0': '/dev/disk/cloud/azure_resource'}
      disk_setup:
        ephemeral0:
          table_type: gpt
          layout: [66, [33,82]]
          overwrite: true
      fs_setup:
        - device: ephemeral0.1
          filesystem: ext4
        - device: ephemeral0.2
          filesystem: swap
      mounts:
        - ["ephemeral0.1", "/mnt"]
        - ["ephemeral0.2", "none", "swap", "sw,nofail,x-systemd.requires=cloud-init.service", "0", "0"]
