---
- name: Install walinuxagent
  command: 
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        sudo -u {{ username }} yay -Sy --noconfirm --aur walinuxagent
        systemctl enable walinuxagent