---
- name: Install firewalld
  command:
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        pacman -Sy --noconfirm firewalld nftables
        firewall-offline-cmd --remove-service=ssh
        firewall-offline-cmd --zone public --add-rich-rule 'rule service name="ssh" accept limit value="2/m"'
        # Enable wireguard
        firewall-offline-cmd --zone=internal --add-service=wireguard
        # firewall-offline-cmd --zone=public --add-port=51820/udp  
        # firewall-offline-cmd --zone=public --add-masquerade
        
        # Required to act as VPN
        firewall-offline-cmd --zone=public --add-interface=eth0
        firewall-offline-cmd --zone=internal --add-interface=wg0

        # Enable firewalld in cloud-init: systemctl enable firewalld
        systemctl disable firewalld

- name: enable logdenied=all
  ansible.builtin.lineinfile:
    path: /mnt/etc/firewalld/firewalld.conf
    regexp: ^\#*LogDenied=(.*)$
    line: LogDenied=all
