---
- name: Install cockpit and open firewalld port
  ignore_errors: true
  command:
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        pacman -Sy --noconfirm cockpit cockpit-podman pcp cockpit-storaged udisks2 sscg nfs-utils # cockpit-packagekit cockpit-machines 
        firewall-offline-cmd --zone=public --add-service=cockpit
        systemctl enable cockpit.socket
        systemctl enable pmlogger.service

- name: set cockpit pam to use oath
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/etc/cockpit/cockpit.conf
    content: |
      [WebService]
      MaxStartups = 2
      UrlRoot = /admin/

      [Session]
      IdleTimeout=60

- name: set cockpit pam to use oath
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/etc/pam.d/cockpit
    content: |
      #%PAM-1.0
      auth      include   system-remote-login
      account   include   system-remote-login
      password  include   system-remote-login
      session   include   system-remote-login
      auth	  required pam_oath.so usersfile=/etc/users.oath window=30 digits=6