---
- name: pacstrap base system with {{ kernel }} and apparmor
  command: pacstrap /mnt base {{ kernel }} linux-firmware openssh base-devel apparmor btrfs-progs nano python sudo wireguard-tools

- name: Run genfstab
  shell: 'genfstab -U /mnt > /mnt/etc/fstab'

- name: "Read a file content"
  shell: |
    cat /mnt/etc/fstab
  register: file_content

- name: "Fail if the fstab does not contain the UUIDs"
  failed_when: file_content.stdout.find('UUID') == -1
  debug: 
    msg: "{{ file_content.stdout }}"

- name: Set hostname to archlinux
  copy: 
    dest: /mnt/etc/hostname
    content: archlinux

- name: set hosts
  copy:
    dest: /mnt/etc/hosts
    content: |
      127.0.0.1	localhost
      ::1		localhost
      127.0.1.1	archlinux.localdomain	archlinux

- name: enable required services
  command:
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        systemctl enable sshd
        systemctl enable btrfs-scrub@-.timer
        sudo systemctl enable btrfs-scrub@home.timer
        systemctl enable systemd-networkd
        systemctl enable systemd-timesyncd
        systemctl enable systemd-homed
        systemctl enable systemd-logind
        systemctl enable systemd-boot-update
        systemctl enable systemd-resolved
        systemctl enable auditd

- name: Set wired networkd config
  copy: 
    dest: /mnt/etc/systemd/network/20-wired.network
    force: yes
    content: |
      [Match]
      Name={{ network_interface_name }}

      [Network]
      DHCP=yes
      Domains=~azure.net ~azure.com ~azurewebsites.net ~windows.net ~azuresynapse.net ~azure-automation.net
      DNSDefaultRoute=false