---
- name: Install yay
  command: 
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        pacman -S --needed git fakeroot --noconfirm

- name: clone yay
  command: 
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        git clone https://aur.archlinux.org/yay-bin.git
        chmod 777 yay-bin

- name: create tmpuser
  command: 
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        useradd -m tmpuser -G wheel -s /bin/bash

- name: allow admin user passwordless sudo
  ansible.builtin.lineinfile:
    path: /mnt/etc/sudoers
    regexp: '^tmpuser ALL=(ALL:ALL) NOPASSWD:ALL'
    line: "tmpuser ALL=(ALL:ALL) NOPASSWD:ALL"

- name: makepkg
  command:
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        cd yay-bin && sudo -u tmpuser makepkg -si --noconfirm

- name: remove cloned yay folder and remove tmpuser
  command: 
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        rm -rf yay-bin
        userdel -r tmpuser

- name: remove tmpuser user passwordless sudo
  ansible.builtin.lineinfile:
    state: absent
    path: /mnt/etc/sudoers
    regexp: '^tmpuser ALL=(ALL:ALL) NOPASSWD:ALL'
    line: "tmpuser ALL=(ALL:ALL) NOPASSWD:ALL"