---
- name: Install restic
  command:
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        pacman -Sy --noconfirm restic
        useradd -m -N -s /usr/sbin/nologin restic

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /mnt/etc/restic
    state: directory
    group: root
    owner: root

- name: ensure file exists
  copy:
    content: ""
    dest: /mnt/etc/restic/root.files
    force: no
    group: root
    owner: root
    mode: 0555

- name: ensure file exists
  copy:
    content: ""
    dest: /mnt/etc/restic/root.env
    force: no
    group: root
    owner: root
    mode: 0555

- name: ensure exclude file exists
  copy:
    content: ".snapshots/*" # exclude btrfs snapshots
    dest: /mnt/etc/restic/root.exclude
    force: no
    group: root
    owner: root
    mode: 0555

- name: create restic@.service
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/etc/systemd/system/restic@.service
    content: |
      [Unit]
      Description=Restic backup on %I
      After=syslog.target
      After=network-online.target

      [Service]
      Environment="http_proxy=http://127.0.0.1:8888"
      Environment="https_proxy=http://127.0.0.1:8888"
      Environment="HTTP_PROXY=http://127.0.0.1:8888"
      Environment="HTTPS_PROXY=http://127.0.0.1:8888"
      Type=oneshot
      User=restic
      ExecStart=/usr/bin/restic backup --files-from /etc/restic/%I.files --exclude-file /etc/restic/%I.exclude
      EnvironmentFile=/etc/restic/%I.env
      AmbientCapabilities=CAP_DAC_READ_SEARCH

      [Install]
      WantedBy=multi-user.target

- name: create restic-no-proxy@.service
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/etc/systemd/system/restic-no-proxy@.service
    content: |
      [Unit]
      Description=Restic backup on %I
      After=syslog.target
      After=network-online.target

      [Service]
      Type=oneshot
      User=restic
      ExecStart=/usr/bin/restic backup --files-from /etc/restic/%I.files --exclude-file /etc/restic/%I.exclude
      EnvironmentFile=/etc/restic/%I.env
      AmbientCapabilities=CAP_DAC_READ_SEARCH

      [Install]
      WantedBy=multi-user.target

- name: create restic-check@.service
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/etc/systemd/system/restic-check@.service
    content: |
      [Unit]
      Description=Restic backup check on %I
      After=syslog.target
      After=network-online.target

      [Service]
      Environment="http_proxy=http://127.0.0.1:8888"
      Environment="https_proxy=http://127.0.0.1:8888"
      Environment="HTTP_PROXY=http://127.0.0.1:8888"
      Environment="HTTPS_PROXY=http://127.0.0.1:8888"
      Type=oneshot
      User=restic
      ExecStart=/usr/bin/restic check --read-data
      EnvironmentFile=/etc/restic/%I.env
      AmbientCapabilities=CAP_DAC_READ_SEARCH

      [Install]
      WantedBy=multi-user.target

- name: create restic-forget-and-prune@.service
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/etc/systemd/system/restic-forget-and-prune@.service
    content: |
      [Unit]
      Description=Restic Forget and Prune on %I
      After=syslog.target
      After=network-online.target

      [Service]
      Environment="http_proxy=http://127.0.0.1:8888"
      Environment="https_proxy=http://127.0.0.1:8888"
      Environment="HTTP_PROXY=http://127.0.0.1:8888"
      Environment="HTTPS_PROXY=http://127.0.0.1:8888"
      Type=oneshot
      User=restic
      ExecStart=/usr/bin/restic forget --prune --keep-daily 7 --keep-weekly 4 --keep-monthly 4 
      EnvironmentFile=/etc/restic/%I.env
      AmbientCapabilities=CAP_DAC_READ_SEARCH

      [Install]
      WantedBy=multi-user.target

- name: create restic@.timer
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/etc/systemd/system/restic@.timer
    content: |
      [Unit]
      Description=Run Restic at 13:00

      [Timer]
      OnCalendar=*-*-* 13:00:00
      Persistent=true

      [Install]
      WantedBy=timers.target

- name: create restic@.timer
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/etc/systemd/system/restic-no-proxy@.timer
    content: |
      [Unit]
      Description=Run Restic at 10:00

      [Timer]
      OnCalendar=*-*-* 10:00:00
      Persistent=true

      [Install]
      WantedBy=timers.target

- name: create restic-forget-and-prune@.timer
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/etc/systemd/system/restic-forget-and-prune@.timer
    content: |
      [Unit]
      Description=Run Restic Forget and Prune Weekly

      [Timer]
      OnCalendar=weekly
      RandomizedDelaySec=8h
      Persistent=true

      [Install]
      WantedBy=timers.target
