---
- name: Install cloud-init
  when: cloud_init
  command:
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        pacman -Sy --noconfirm cloud-init cloud-utils gptfdisk udftools
        systemctl enable cloud-init.service
        systemctl enable cloud-final.service

- name: set ntfs3 as default to read cloud-init
  when: cloud_init
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/etc/udev/rules.d/ntfs3_by_default.rules
    content: |
      SUBSYSTEM=="block", ENV{ID_FS_TYPE}=="ntfs", ENV{ID_FS_TYPE}="ntfs3"

- name: set cloud-init cloud.cfg
  when: cloud_init
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/etc/cloud/cloud.cfg
    content: |
      users:
        - default
      disable_root: true
      preserve_hostname: false
      datasource_list: [ Azure ]

      # The modules that run in the 'init' stage
      cloud_init_modules:
      - migrator
      - seed_random
      - bootcmd
      - write-files
      - growpart
      - resizefs
      - disk_setup
      - mounts
      - set_hostname
      - update_hostname
      - update_etc_hosts
      - ca-certs
      - rsyslog
      - users-groups
      - ssh

      # The modules that run in the 'config' stage
      cloud_config_modules:
      - ssh-import-id
      - keyboard
      - locale
      - set-passwords
      - ntp
      - timezone
      - runcmd

      # The modules that run in the 'final' stage
      cloud_final_modules:
      - package-update-upgrade-install
      - write-files-deferred
      - mcollective
      - reset_rmc
      - refresh_rmc_and_interface
      - scripts-vendor
      - scripts-per-once
      - scripts-per-boot
      - scripts-per-instance
      - scripts-user
      - ssh-authkey-fingerprints
      - keys-to-console
      - install-hotplug
      - phone-home
      - wireguard
      - final-message
      - power-state-change

      system_info:
        distro: arch
        default_user:
          name: {{ username }}
          lock_passwd: False
          gecos: arch Cloud User
          groups: [wheel, users, uucp]
          sudo: ["ALL=(ALL) NOPASSWD:ALL"]
          shell: /bin/bash
        paths:
          cloud_dir: /var/lib/cloud/
          templates_dir: /etc/cloud/templates/
        ssh_svcname: sshd