---
- name: Install caddy
  command:
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        pacman -Sy --noconfirm caddy
        firewall-offline-cmd --zone=public --add-port=80/tcp
        firewall-offline-cmd --zone=public --add-port=443/tcp 
        firewall-offline-cmd --zone=internal --add-port=80/tcp
        firewall-offline-cmd --zone=internal --add-port=443/tcp 

- name: set caddyfile
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/etc/caddy/Caddyfile
    content: |
      # Replace domain with the fqdn during cloud-init
      <domain> {
        @insecureadmin {
          not remote_ip 192.168.0.0/16 172.16.0.0/12 10.0.0.0/8
          path /admin*
        }
        respond @insecureadmin "Access Denied" 403
        
        reverse_proxy /admin/* localhost:9090 {
          transport http {
              tls_insecure_skip_verify
          }
        }
      }

- name: Create /usr/lib/systemd/system/caddy.service.d directory
  ansible.builtin.file:
    path: /mnt/usr/lib/systemd/system/caddy.service.d
    state: directory

- name: set caddy systemd proxy settings
  copy:
    owner: root
    group: root
    force: yes
    dest: /mnt/usr/lib/systemd/system/caddy.service.d/http_proxy.conf
    content: |
      [Service]
      Environment="http_proxy=http://127.0.0.1:8888"
      Environment="https_proxy=http://127.0.0.1:8888"
      Environment="HTTP_PROXY=http://127.0.0.1:8888"
      Environment="HTTPS_PROXY=http://127.0.0.1:8888"
