---
- name: Install firewalld
  command:
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        pacman -Sy --noconfirm firewalld nftables
        firewall-offline-cmd --remove-service=ssh
        firewall-offline-cmd --zone public --add-rich-rule 'rule service name="ssh" accept limit value="2/m"'
        # Enable firewalld in cloud-init: systemctl enable firewalld
        systemctl enable firewalld

- name: enable logdenied=all
  ansible.builtin.lineinfile:
    path: /mnt/etc/firewalld/firewalld.conf
    regexp: ^\#*LogDenied=(.*)$
    line: LogDenied=all