---
- name: Install yay
  command: 
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        pacman -S --needed git --noconfirm

- name: clone yay
  command: 
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        git clone https://aur.archlinux.org/yay-bin.git
        chmod 777 yay-bin

- name: makepkg
  when: username is defined
  command:
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        cd yay-bin && sudo -u {{ username }} makepkg -si --noconfirm

- name: makepkg
  when: lookup('env', 'USER') != "root" and username is not defined
  command:
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        cd yay-bin && makepkg -si --noconfirm

- name: remove cloned yay folder 
  command: 
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        rm -rf yay-bin