---
- name: Install cockpit and open firewalld port
  ignore_errors: true
  command:
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        pacman -Sy --noconfirm cockpit cockpit-machines cockpit-podman cockpit-packagekit cockpit-storaged udisks2
        firewall-cmd --zone public --permanent --add-port=9090/tcp
        systemctl enable cockpit.socket