---
- name: set root partition for bios
  set_fact:
    root_partition_number: "1"

- name: Label {{ install_device_name }} as msdos
  when: not root_mounted
  community.general.parted:
      device: "{{ install_device_name }}"
      label: msdos

- name: Create btrfs partition on bios
  when: not root_mounted
  community.general.parted:
    device: "{{ install_device_name }}"
    number: 1
    state: present
    part_start: 1MB
    part_end: 100%
    fs_type: btrfs