---
- name: enable apparmor
  command:
    argv:
      - /usr/bin/arch-chroot
      - /mnt
      - /bin/bash
      - -c
      - |
        systemctl enable apparmor
        #sudo -u {{ username }} yay -Sy --noconfirm --aur apparmor.d-git --overwrite '*'

- name: enable caching of apparmor profiles
  ansible.builtin.lineinfile:
    path: /mnt/etc/apparmor/parser.conf
    line: write-cache
    create: yes

